.\" Manpage for RSS feed reader.
.\" Contact ep4g11@soton.ac.uk.
.TH man 1 "24th Februrary 2012" "1.2" "info6005-cw1-ep4g11 manpage"
.SH NAME
info6005-cw1-ep4g11 \- Command line RSS feed reader. 
.SH SYNOPSIS
getfeeds
.SH DESCRIPTION
RSS Feed Reader running from command line. By default shows the 10 last news titles published on BBC website.
.SH OPTIONS
.IP --feeds
Provide additional RSS feed source(.xml)
.IP --items
Provide number of items to be shown on console.
.SH SEE ALSO

.SH BUGS
No.
.SH AUTHOR
Eleftherios Panagoulis (ep4g11@soton.ac.uk)
